# Generated by Django 5.2 on 2025-04-30 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_status_codeverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeverification',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 30, 13, 36, 35, 975412, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
