# Generated by Django 5.2 on 2025-05-02 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_codeverification_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Telefon raqami +998 bilan boshlanib, jami 13 ta raqamdan iborat bo‘lishi kerak (masalan: +998901234567)', regex='^\\+998\\d{9}$')]),
        ),
    ]
